image: rocker/rstudio  
test:  
   script:
    - apt-get install -y libgit2-dev
    - R -e 'install.packages(c("ggplot2", "devtools", "scales", "viridis", "knitr", "rmarkdown", "testthat", "RColorBrewer", "covr"))'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
    - R -e 'devtools::test()'
